.PHONY: install
install:
	npm install client

.PHONY: build
build: install
	npm run build

.PHONY: fmt
fmt:
	npm run fmt

.PHONY: clean
clean:
	rm -rf node_modules

.PHONY: unit-test
unit-test:
	npm run unit-test

.PHONY: smoke-test
smoke-test:
	npm run smoke-test
