include ../../common.mk

.PHONY: clean
clean:
	echo "not yet defined"

# Build the ElasticBeanstalk configuration and deployment bundle,
# such that deployment can be done with a simple `eb deploy`.
# Presumes that a top-level `make build-client` has been done to 
# create the client static assets.
#
.PHONY: build
build:
	echo "not yet defined"
