#!/usr/bin/env python3
import argparse
import errno
import socket
import sys
import time

parser = argparse.ArgumentParser(description='Wait for a port to be available.')
parser.add_argument('port', type=int, help='port to wait for')
parser.add_argument('--sleep-increment', type=int, default=1.0, help='sleep duration in between checks of the port')
parser.add_argument('--timeout', type=int, default=20.0, help='How long should we wait before timing out?')
parser.add_argument('--await-active', default=False, action='store_true', help='Wait for the port to be active or free?')

args = parser.parse_args()

start = time.time()

port_in_use = True

def condition_reached(port_in_use):
    return port_in_use if args.await_active else not port_in_use

while not condition_reached(port_in_use):
    # halt if we've reached the timeout
    elapsed = time.time() - start
    if elapsed > args.timeout:
        print(f"Timed out while waiting for port {args.port}")
        sys.exit(1)

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        try:
            s.bind(('localhost', args.port))
            port_in_use = False
        except socket.error as e:
            if e.errno == errno.EADDRINUSE:
                print(f"Waiting for port {args.port} to be available... sleeping for {args.sleep_increment} seconds.")
                time.sleep(args.sleep_increment)
            else:
                raise e

print(f"Port {args.port} is {'active' if args.await_active else 'free'}!")
