#!/usr/bin/env bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)

cd ${PROJECT_ROOT}

./scripts/dev_setup

source venv/bin/activate

cd client

export CXG_OPTIONS=${CXG_OPTIONS:---debug}

make start-server
