export default [
  "cell",
  "primary cultured cell",
  "native cell",
  "fibroblast neural crest derived",
  "neuronal receptor cell",
  "early embryonic cell",
  "migratory cranial neural crest cell",
  "cultured cell",
  "migratory trunk neural crest cell",
  "germ line stem cell",
  "male germ cell",
  "male germ line stem cell",
  "spermatocyte",
  "spermatid",
  "sperm",
  "spermatogonium",
  "female germ cell",
  "female germ line stem cell",
  "oocyte",
  "oogonial cell",
  "egg cell",
  "invertebrate nurse cell",
  "smooth muscle cell neural crest derived",
  "CNS neuron (sensu Nematoda and Protostomia)",
  "neuron neural crest derived",
  "glioblast",
  "neuroblast",
  "neuroplacodal cell",
  "apocrine cell",
  "stem cell",
  "single fate stem cell",
  "epithelial fate stem cell",
  "hematopoietic stem cell",
  "erythroid progenitor cell",
  "germ line cell",
  "monoblast",
  "mature eosinophil",
  "neutrophilic myeloblast",
  "mature basophil",
  "neuronal stem cell",
  "multi fate stem cell",
  "common myeloid progenitor",
  "megakaryocyte-erythroid progenitor cell",
  "common lymphoid progenitor",
  "totipotent stem cell",
  "bone matrix secreting cell",
  "non-terminally differentiated cell",
  "myoblast",
  "fibroblast",
  "chondroblast",
  "ameloblast",
  "odontoblast",
  "cementoblast",
  "osteoblast",
  "ciliated cell",
  "ependymal cell",
  "epithelial cell",
  "ciliated epithelial cell",
  "duct epithelial cell",
  "branched duct epithelial cell",
  "blood vessel endothelial cell",
  "non-branched duct epithelial cell",
  "barrier epithelial cell",
  "columnar/cuboidal epithelial cell",
  "squamous epithelial cell",
  "mesothelial cell",
  "peridermal cell",
  "stratified epithelial cell",
  "circulating cell",
  "blood cell",
  "epithelial cell of lung",
  "epithelial cell of pancreas",
  "T cell",
  "germ line stem cell (sensu Vertebrata)",
  "germ line stem cell (sensu Nematoda and Protostomia)",
  "male germ line stem cell (sensu Nematoda and Protostomia)",
  "female germ line stem cell (sensu Nematoda and Protostomia)",
  "male germ line stem cell (sensu Vertebrata)",
  "female germ line stem cell (sensu Vertebrata)",
  "Kupffer cell",
  "osteoclast",
  "granulocyte",
  "neuron associated cell",
  "mature neutrophil",
  "mast cell",
  "sensory epithelial cell",
  "interneuron",
  "motor neuron",
  "sensory neuron",
  "polymodal neuron",
  "bipolar neuron",
  "multipolar neuron",
  "pseudounipolar neuron",
  "unipolar neuron",
  "autonomic neuron",
  "cholinergic neuron",
  "adrenergic neuron",
  "peptidergic neuron",
  "peripheral neuron",
  "columnar neuron",
  "mononuclear phagocyte",
  "surface ectodermal cell",
  "endothelial cell",
  "pioneer neuron",
  "CNS neuron (sensu Vertebrata)",
  "basket cell",
  "cerebellar Golgi cell",
  "granule cell",
  "Purkinje cell",
  "stellate neuron",
  "neuron associated cell (sensu Vertebrata)",
  "glial cell (sensu Nematoda and Protostomia)",
  "glial cell",
  "macroglial cell",
  "astrocyte",
  "oligodendrocyte",
  "microglial cell",
  "neuron associated cell (sensu Nematoda and Protostomia)",
  "gut endothelial cell",
  "corneal endothelial cell",
  "neurectodermal cell",
  "mesenchymal stem cell",
  "fibrocyte",
  "fat cell",
  "osteocyte",
  "chondrocyte",
  "odontocyte",
  "cementocyte",
  "hyalocyte",
  "guidepost cell",
  "professional antigen presenting cell",
  "simple columnar epithelial cell",
  "pigment cell",
  "melanocyte",
  "visual pigment cell",
  "glandular epithelial cell",
  "secretory cell",
  "exocrine cell",
  "glycosaminoglycan secreting cell",
  "protein secreting cell",
  "peptic cell",
  "surfactant secreting cell",
  "club cell",
  "seromucus secreting cell",
  "goblet cell",
  "acid secreting cell",
  "parietal cell",
  "endocrine cell",
  "enteroendocrine cell",
  "neuroendocrine cell",
  "chromaffin cell",
  "peptide hormone secreting cell",
  "insulin secreting cell",
  "type B pancreatic cell",
  "glucagon secreting cell",
  "pancreatic A cell",
  "somatostatin secreting cell",
  "pancreatic D cell",
  "steroid hormone secreting cell",
  "luteal cell",
  "ecdysteroid secreting cell",
  "testosterone secreting cell",
  "Leydig cell",
  "progesterone secreting cell",
  "estradiol secreting cell",
  "metabolising cell",
  "hepatocyte",
  "contractile cell",
  "myoepithelial cell",
  "myofibroblast cell",
  "muscle cell",
  "cell of skeletal muscle",
  "slow muscle cell",
  "fast muscle cell",
  "smooth muscle cell",
  "cardiac muscle cell (sensu Arthopoda)",
  "flight muscle cell",
  "receptor cell",
  "pain receptor cell",
  "mechanoreceptor cell",
  "touch receptor cell",
  "auditory hair cell",
  "gravity sensitive cell",
  "acceleration receptive cell",
  "thermoreceptor cell",
  "chemoreceptor cell",
  "olfactory receptor cell",
  "pH receptor cell",
  "taste receptor cell",
  "photoreceptor cell",
  "electrically active cell",
  "absorptive cell",
  "lining cell",
  "synovial cell",
  "barrier cell",
  "Sertoli cell",
  "insulating cell",
  "myelinating Schwann cell",
  "motile cell",
  "ectodermal cell",
  "mesodermal cell",
  "endodermal cell",
  "anucleate cell",
  "single nucleate cell",
  "binucleate cell",
  "multinucleate cell",
  "erythrocyte",
  "platelet",
  "phagocyte",
  "macrophage",
  "B cell",
  "keratinizing barrier epithelial cell",
  "non keratinizing barrier epithelial cell",
  "brush border epithelial cell",
  "stratified squamous epithelial cell",
  "stratified cuboidal epithelial cell",
  "Merkel cell",
  "glial cell (sensu Vertebrata)",
  "transitional epithelial cell",
  "Mauthner neuron",
  "Rohon-Beard neuron",
  "hatching gland cell",
  "extramedullary cell",
  "eurydendroid cell",
  "eukaryotic cell",
  "uric acid accumulating cell",
  "Mycetozoan cell",
  "hyphal cell",
  "eye photoreceptor cell",
  "structural cell",
  "somatotropin secreting cell",
  "gamete",
  "pole cell",
  "crystallin accumulating cell",
  "tracheal epithelial cell",
  "metal ion accumulating cell",
  "copper accumulating cell",
  "iron accumulating cell",
  "keratin accumulating cell",
  "keratinocyte",
  "serous secreting cell",
  "milk secreting cell",
  "tears secreting cell",
  "sebum secreting cell",
  "sweat secreting cell",
  "mucus secreting cell",
  "seminal fluid secreting cell",
  "pneumocyte",
  "lysozyme secreting cell",
  "metanephric mesenchyme stem cell",
  "stuff accumulating cell",
  "glycogen accumulating cell",
  "extracellular matrix secreting cell",
  "myelin accumulating cell",
  "oxygen accumulating cell",
  "migratory neural crest cell",
  "vegetative cell (sensu Fungi)",
  "mesenchyme condensation cell",
  "adrenal medulla chromaffin cell",
  "neuroblast (sensu Vertebrata)",
  "neuroblast (sensu Nematoda and Protostomia)",
  "glioblast (sensu Vertebrata)",
  "glioblast (sensu Nematoda and Protostomia)",
  "pigment cell (sensu Nematoda and Protostomia)",
  "pigment cell (sensu Vertebrata)",
  "visual pigment cell (sensu Vertebrata)",
  "dental papilla cell",
  "hair follicle dermal papilla cell",
  "scleral cell",
  "choroidal cell of the eye",
  "extraembryonic cell",
  "amnioserosal cell",
  "trophoblast cell",
  "epiblast cell",
  "blastoderm cell",
  "blastemal cell",
  "multi-potent skeletal muscle stem cell",
  "hair matrix stem cell",
  "stratified epithelial stem cell",
  "sphincter associated smooth muscle cell",
  "vascular associated smooth muscle cell",
  "morula cell",
  "gastrula cell",
  "epidermal cell",
  "animal zygote",
  "sheath cell (sensu Nematoda)",
  "protoplast",
  "tormogen cell",
  "histoblast",
  "trichogen cell",
  "humidity receptor cell",
  "tracheoblast",
  "support cell (sensu Nematoda and Protostomia)",
  "sensory processing neuron",
  "thecogen cell",
  "neurosecretory neuron",
  "scolopale cell",
  "nephrogenic mesenchyme stem cell",
  "ligament cell",
  "prohemocyte (sensu Nematoda and Protostomia)",
  "attachment cell",
  "hemocyte (sensu Nematoda and Protostomia)",
  "tendon cell",
  "socket cell (sensu Nematoda)",
  "blood cell (sensu Nematoda and Protostomia)",
  "podocyte (sensu Diptera)",
  "crystal cell",
  "electrically responsive cell",
  "plasmatocyte",
  "procrystal cell",
  "lamellocyte",
  "ganglion interneuron",
  "polygonal cell",
  "macrophage (sensu Diptera)",
  "CNS interneuron",
  "electrically signaling cell",
  "neuroepidermoblast",
  "CNS short range interneuron",
  "scolopidial ligament cell",
  "male gamete",
  "scolopidial sheath cell",
  "CNS long range interneuron",
  "flatworm hypodermal cell",
  "polyploid cell",
  "haploid cell",
  "diploid cell",
  "polytene cell",
  "endopolyploid cell",
  "arcade cell",
  "seam cell",
  "syncytial epithelial cell",
  "coelomocyte",
  "mitogenic signaling cell",
  "tip cell",
  "excretory cell",
  "pore cell",
  "scaffold cell",
  "GLR cell",
  "yolk cell",
  "imaginal disc cell",
  "xanthophore cell",
  "iridophore",
  "reticular cell",
  "eccrine cell",
  "alkali secreting cell",
  "vaginal lubricant secreting cell",
  "gonadtroph",
  "luteinizing hormone secreting cell",
  "prolactin secreting cell",
  "melanocyte stimulating hormone secreting cell",
  "follicle stem cell",
  "follicular dendritic cell",
  "calcitonin secreting cell",
  "obliquely striated muscle cell",
  "apoptosis fated cell",
  "chief cell of parathyroid gland",
  "carbohydrate secreting cell",
  "white fat cell",
  "brown fat cell",
  "dendritic cell",
  "thyroid hormone secreting cell",
  "Langerhans cell",
  "epinephrine secreting cell",
  "mineralocorticoid secreting cell",
  "biogenic amine secreting cell",
  "serotonin secreting cell",
  "noradrenergic cell",
  "glucocorticoid secreting cell",
  "adepithelial cell",
  "epidermal cell (sensu arthropoda)",
  "epidermoblast",
  "cardioblast (sensu Arthropoda)",
  "adrenocorticotropic hormone secreting cell",
  "neuroglioblast",
  "ganglion mother cell",
  "digestive enzyme secreting cell",
  "defensive cell",
  "pericardial nephrocyte",
  "thyrotroph",
  "follicle cell",
  "oxytocin stimulating hormone secreting cell",
  "vasopressin stimulating hormone secreting cell",
  "secretin stimulating hormone secreting cell",
  "cholecystokin stimulating hormone secreting cell",
  "juvenile hormone secreting cell",
  "bombesin stimulating hormone secreting cell",
  "connective tissue type mast cell",
  "mucosal type mast cell",
  "garland cell",
  "oenocyte",
  "visible light photoreceptor cell",
  "scotopic photoreceptor cell",
  "photopic photoreceptor cell",
  "CD4-positive helper T cell",
  "UV sensitive photoreceptor cell",
  "blue sensitive photoreceptor cell",
  "green sensitive photoreceptor cell",
  "red sensitive photoreceptor cell",
  "inhibitory interneuron",
  "stromal cell",
  "follicular epithelial cell",
  "granulosa cell",
  "type D enteroendocrine cell",
  "theca cell",
  "enterochromaffin-like cell",
  "substance P secreting cell",
  "enkephalin secreting cell",
  "endorphin secreting cell",
  "type G enteroendocrine cell",
  "gastrin secreting cell",
  "paneth cell",
  "androgen binding protein secreting cell",
  "paracrine cell",
  "cardiac muscle myoblast",
  "smooth muscle myoblast",
  "skeletal muscle myoblast",
  "perineuronal satellite cell",
  "macrophage derived foam cell",
  "phagocyte (sensu Vertebrata)",
  "phagocyte (sensu Nematoda and Protostomia)",
  "prokaryotic cell",
  "fungal cell",
  "mononuclear cytotrophoblast cell",
  "spheroplast",
  "syncytiotrophoblast cell",
  "afferent neuron",
  "efferent neuron",
  "nitrergic neuron",
  "pigmented epithelial cell",
  "primary neuron",
  "primary sensory neuron",
  "CAP motoneuron",
  "primary motor neuron",
  "primary interneuron",
  "secondary neuron",
  "secondary motor neuron",
  "neuron",
  "melanoblast",
  "lymphocyte",
  "slowly adapting mechanoreceptor cell",
  "T-helper 1 cell",
  "T-helper 2 cell",
  "proerythroblast",
  "animal cell",
  "basophilic erythroblast",
  "polychromatophilic erythroblast",
  "unimodal nocireceptor",
  "orthochromatic erythroblast",
  "megakaryocyte progenitor cell",
  "gastrin stimulating hormone secreting cell",
  "neuronal brush cell",
  "megakaryocyte",
  "granulocyte monocyte progenitor cell",
  "reticulocyte",
  "promonocyte",
  "band form neutrophil",
  "amacrine cell",
  "nucleate erythrocyte",
  "endospore",
  "neutrophilic promyelocyte",
  "fat body cell",
  "angioblastic mesenchymal cell",
  "polymodal nocireceptor",
  "amine precursor uptake and decarboxylation cell",
  "cardiac mesenchymal cell",
  "parafollicular cell",
  "leucophore",
  "retinal cone cell",
  "erythrophore",
  "corneal epithelial cell",
  "monocyte",
  "type EC enteroendocrine cell",
  "experimentally modified cell in vitro",
  "border follicle cell",
  "neutrophilic myelocyte",
  "peritoneal macrophage",
  "neutrophilic metamyelocyte",
  "alveolar macrophage",
  "enterocyte",
  "germ cell",
  "cold sensing thermoreceptor cell",
  "odontoclast",
  "cochlear inner hair cell",
  "small luteal cell",
  "warmth sensing thermoreceptor cell",
  "large luteal cell",
  "androgen secreting cell",
  "skeletal muscle satellite cell",
  "enucleate erythrocyte",
  "sexual spore",
  "microconidium",
  "pyramidal neuron",
  "conidium",
  "heterokaryon",
  "outer hair cell",
  "pressoreceptor cell",
  "dikaryon",
  "retinal rod cell",
  "fungal asexual spore",
  "macroconidium",
  "ascospore",
  "zygospore",
  "vestibular hair cell",
  "eosinophil progenitor cell",
  "eosinophilic myelocyte",
  "basophil progenitor cell",
  "basophilic myelocyte",
  "basidiospore",
  "GABAergic neuron",
  "sheath cell",
  "support cell (sensu Nematoda)",
  "fusion competent myoblast",
  "acinar cell",
  "natural killer cell",
  "CD4-positive, alpha-beta T cell",
  "CD8-positive, alpha-beta T cell",
  "olfactory granule cell",
  "transporting cell",
  "photosynthetic cell",
  "storage cell",
  "supportive cell",
  "labyrinth supporting cell",
  "hepatic stellate cell",
  "Hensen cell",
  "Claudius cell",
  "Deiter's cell",
  "Mueller cell",
  "chromophil cell of anterior pituitary gland",
  "acidophil cell of pars distalis of adenohypophysis",
  "basophil cell of pars distalis of adenohypophysis",
  "chromophobe cell",
  "folliculostellate cell",
  "Bergmann glial cell",
  "pituicyte",
  "basal cell",
  "multinucleated giant cell",
  "kidney granular cell",
  "prickle cell",
  "mesangial cell",
  "mucous neck cell",
  "pinealocyte",
  "glomerular visceral epithelial cell",
  "primary oocyte",
  "secondary oocyte",
  "primary spermatocyte",
  "secondary spermatocyte",
  "cuticle secreting cell",
  "eggshell secreting cell",
  "glycocalyx secreting cell",
  "distal tip cell (sensu Nematoda)",
  "neuroglioblast (sensu Nematoda)",
  "valve cell",
  "closable valve cell",
  "permanently open valve cell",
  "fenestrated cell",
  "collagen secreting cell",
  "pericyte cell",
  "primordial germ cell",
  "centripetally migrating follicle cell",
  "Kenyon cell",
  "interfollicle cell",
  "female gamete",
  "cap cell",
  "gut absorptive cell",
  "commissural neuron",
  "glutamatergic neuron",
  "muscle precursor cell",
  "radial glial cell",
  "M cell of gut",
  "ependymoglial cell",
  "littoral cell of liver",
  "cerebrospinal fluid secreting cell",
  "R1 photoreceptor cell",
  "perijunctional fibroblast",
  "myoendocrine cell",
  "R2 photoreceptor cell",
  "stellate interneuron",
  "terminal Schwann cell",
  "neuroglioform cell",
  "R3 photoreceptor cell",
  "Cajal-Retzius cell",
  "PP cell",
  "R4 photoreceptor cell",
  "paraganglial type 1 cell",
  "dopaminergic neuron",
  "paraganglia type 2 cell",
  "R5 photoreceptor cell",
  "sustentacular cell",
  "endothelial tip cell",
  "R6 photoreceptor cell",
  "choroid plexus epithelial cell",
  "R7 photoreceptor cell",
  "leptomeningeal cell",
  "R8 photoreceptor cell",
  "neurecto-epithelial cell",
  "cumulus cell",
  "stratum granulosum cell",
  "corona radiata cell",
  "embryonic crystal cell",
  "lymph gland crystal cell",
  "fusimotor neuron",
  "compound eye cone cell",
  "posterior cone cell (sensu Endopterygota)",
  "anterior cone cell (sensu Endopterygota)",
  "equatorial cone cell (sensu Endopterygota)",
  "cystoblast",
  "somatic stem cell",
  "heterocyst",
  "nitrogen fixing cell",
  "chlamydospore",
  "primary pigment cell",
  "secondary pigment cell",
  "tertiary pigment cell",
  "leading edge cell",
  "urothelial cell",
  "amoeboid cell",
  "lymph gland plasmatocyte",
  "embryonic gland plasmatocyte",
  "lymph gland hemocyte",
  "embryonic gland hemocyte",
  "striated muscle cell",
  "leukocyte",
  "retinal ganglion cell",
  "spinal accessory motor neuron",
  "periarticular chondrocyte",
  "hypertrophic chondrocyte",
  "columnar chondrocyte",
  "retina horizontal cell",
  "cardiac muscle cell",
  "cyanophore",
  "retinal bipolar neuron",
  "ON-bipolar cell",
  "OFF-bipolar cell",
  "rod bipolar cell",
  "cone retinal bipolar cell",
  "type 1 cone bipolar cell (sensu Mus)",
  "type 2 cone bipolar cell (sensu Mus)",
  "type 3 cone bipolar cell (sensu Mus)",
  "type 4 cone bipolar cell (sensu Mus)",
  "type 5 cone bipolar cell (sensu Mus)",
  "type 6 cone bipolar cell (sensu Mus)",
  "type 7 cone bipolar cell (sensu Mus)",
  "type 8 cone bipolar cell (sensu Mus)",
  "type 9 cone bipolar cell (sensu Mus)",
  "nucleated thrombocyte",
  "myeloid cell",
  "erythroid lineage cell",
  "erythroblast",
  "myeloid leukocyte",
  "basophil",
  "immature basophil",
  "basophilic metamyelocyte",
  "band form basophil",
  "eosinophil",
  "immature eosinophil",
  "eosinophilic metamyelocyte",
  "band form eosinophil",
  "neutrophil",
  "immature neutrophil",
  "mesangial phagocyte",
  "mononuclear osteoclast",
  "multinuclear osteoclast",
  "multinuclear odontoclast",
  "mononuclear odontoclast",
  "myeloid dendritic cell",
  "multinucleated phagocyte",
  "plasmacytoid dendritic cell",
  "mature B cell",
  "plasma cell",
  "memory B cell",
  "naive B cell",
  "alpha-beta T cell",
  "immature alpha-beta T cell",
  "mature alpha-beta T cell",
  "CD4-positive, CD25-positive, alpha-beta regulatory T cell",
  "CD4-positive, alpha-beta intraepithelial T cell",
  "CD8-positive, alpha-beta cytotoxic T cell",
  "CD8-positive, alpha-beta regulatory T cell",
  "CD8-alpha-beta-positive, alpha-beta intraepithelial T cell",
  "alpha-beta intraepithelial T cell",
  "gamma-delta T cell",
  "immature gamma-delta T cell",
  "mature gamma-delta T cell",
  "gamma-delta intraepithelial T cell",
  "CD8-alpha alpha positive, gamma-delta intraepithelial T cell",
  "CD4-negative CD8-negative gamma-delta intraepithelial T cell",
  "immature single positive thymocyte",
  "DN2 thymocyte",
  "DN3 thymocyte",
  "DN4 thymocyte",
  "double-positive, alpha-beta thymocyte",
  "CD4-positive, alpha-beta thymocyte",
  "CD8-positive, alpha-beta thymocyte",
  "memory T cell",
  "mature NK T cell",
  "regulatory T cell",
  "immature B cell",
  "precursor B cell",
  "transitional stage B cell",
  "B-1 B cell",
  "B-1a B cell",
  "B-1b B cell",
  "B-2 B cell",
  "immature natural killer cell",
  "mature natural killer cell",
  "pro-NK cell",
  "pro-B cell",
  "pro-T cell",
  "thromboblast",
  "basophilic myeloblast",
  "basophilic promyelocyte",
  "mast cell progenitor",
  "eosinophilic myeloblast",
  "eosinophilic promyelocyte",
  "neutrophil progenitor cell",
  "myeloblast",
  "promyelocyte",
  "hematopoietic multipotent progenitor cell",
  "lymphoid lineage restricted progenitor cell",
  "myeloid lineage restricted progenitor cell",
  "immature conventional dendritic cell",
  "mature conventional dendritic cell",
  "mononuclear cell",
  "follicular B cell",
  "germinal center B cell",
  "marginal zone B cell",
  "vestibular dark cell",
  "ciliated olfactory receptor neuron",
  "microvillous olfactory receptor neuron",
  "crypt olfactory receptor neuron",
  "serotonergic neuron",
  "neuromast mantle cell",
  "neuromast support cell",
  "olfactory epithelial support cell",
  "interneuromast cell",
  "sensory hair cell",
  "neuromast hair cell",
  "slow muscle myoblast",
  "fast muscle myoblast",
  "classical monocyte",
  "elicited macrophage",
  "suppressor macrophage",
  "inflammatory macrophage",
  "tissue-resident macrophage",
  "gastrointestinal tract (lamina propria) macrophage",
  "thymic macrophage",
  "secondary lymphoid organ macrophage",
  "lymph node macrophage",
  "tonsillar macrophage",
  "Peyer's patch macrophage",
  "splenic macrophage",
  "splenic marginal zone macrophage",
  "splenic metallophillic macrophage",
  "splenic red pulp macrophage",
  "non-classical monocyte",
  "splenic white pulp macrophage",
  "splenic tingible body macrophage",
  "central nervous system macrophage",
  "meningeal macrophage",
  "choroid-plexus macrophage",
  "perivascular macrophage",
  "thymic medullary macrophage",
  "thymic cortical macrophage",
  "mucosa-associated lymphoid tissue macrophage",
  "gut-associated lymphoid tissue macrophage",
  "nasal and broncial associated lymphoid tissue macrophage",
  "lymph node subcapsular sinus macrophage",
  "lymph node tingible body macrophage",
  "myeloid suppressor cell",
  "alternatively activated macrophage",
  "foam cell",
  "smooth muscle cell derived foam cell",
  "thymocyte",
  "DN1 thymic pro-T cell",
  "naive thymus-derived CD4-positive, alpha-beta T cell",
  "activated CD4-positive, alpha-beta T cell",
  "CD4-positive, alpha-beta memory T cell",
  "naive T cell",
  "T-helper 17 cell",
  "naive thymus-derived CD8-positive, alpha-beta T cell",
  "Tr1 cell",
  "induced T-regulatory cell",
  "natural T-regulatory cell",
  "central memory CD4-positive, alpha-beta T cell",
  "effector memory CD4-positive, alpha-beta T cell",
  "activated CD8-positive, alpha-beta T cell",
  "central memory CD8-positive, alpha-beta T cell",
  "CD8-positive, alpha-beta cytokine secreting effector T cell",
  "CD8-positive, alpha-beta memory T cell",
  "cytotoxic T cell",
  "effector T cell",
  "helper T cell",
  "effector memory CD8-positive, alpha-beta T cell",
  "immature NK T cell",
  "CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell",
  "dendritic epidermal T cell",
  "Tc1 cell",
  "Tc2 cell",
  "CD8-positive, CD25-positive, alpha-beta regulatory T cell",
  "CD8-positive, CD28-negative, alpha-beta regulatory T cell",
  "type I NK T cell",
  "type II NK T cell",
  "CD4-positive type I NK T cell",
  "CD4-negative, CD8-negative type I NK T cell",
  "activated CD4-positive type I NK T cell",
  "CD4-positive type I NK T cell secreting interferon-gamma",
  "CD4-positive type I NK T cell secreting interleukin-4",
  "activated CD4-negative, CD8-negative type I NK T cell",
  "CD4-negative, CD8-negative type I NK T cell secreting interferon-gamma",
  "CD4-negative, CD8-negative type I NK T cell secreting interleukin-4",
  "activated type II NK T cell",
  "type II NK T cell secreting interferon-gamma",
  "type II NK T cell secreting interleukin-4",
  "CD4-positive, alpha-beta cytotoxic T cell",
  "CD4-negative, CD8-negative, alpha-beta intraepithelial T cell",
  "early lymphoid progenitor",
  "pre-natural killer cell",
  "CD16-negative, CD56-bright natural killer cell",
  "CD16-positive, CD56-dim natural killer cell",
  "mucosal invariant T cell",
  "thymic conventional dendritic cell",
  "thymic plasmacytoid dendritic cell",
  "Be1 Cell",
  "Be2 cell",
  "lymphocyte of B lineage",
  "antibody secreting cell",
  "IgE plasma cell",
  "IgE memory B cell",
  "IgD plasmablast",
  "IgE plasmablast",
  "IgE short lived plasma cell",
  "preBCR-positive large pre-B-II cell",
  "preBCR-negative large pre-B-II cell",
  "small pre-B-II cell",
  "pre-B-II cell",
  "pre-B-I cell",
  "large pre-B-II cell",
  "T1 B cell",
  "T2 B cell",
  "T3 B cell",
  "Bm1 B cell",
  "Bm2 B cell",
  "Bm3-delta B cell",
  "Bm2' B cell",
  "Bm3 B cell",
  "Bm4 B cell",
  "Bm5 B cell",
  "Be cell",
  "regulatory B cell",
  "unswitched memory B cell",
  "IgM memory B cell",
  "class switched memory B cell",
  "IgA memory B cell",
  "long lived plasma cell",
  "short lived plasma cell",
  "IgA short lived plasma cell",
  "IgG short lived plasma cell",
  "IgM short lived plasma cell",
  "IgG memory B cell",
  "plasmablast",
  "double negative memory B cell",
  "IgG plasmablast",
  "IgM plasmablast",
  "IgA plasmablast",
  "IgG plasma cell",
  "IgM plasma cell",
  "IgA plasma cell",
  "hematopoietic cell",
  "CD11c-low plasmacytoid dendritic cell",
  "conventional dendritic cell",
  "CD11c-negative plasmacytoid dendritic cell",
  "immature CD11c-low plasmacytoid dendritic cell",
  "mature CD11c-low plasmacytoid dendritic cell",
  "immature CD11c-negative plasmacytoid dendritic cell",
  "CD34-positive, CD38-positive common myeloid progenitor OR CD34-positive, CD38-positive common lymphoid progenitor",
  "mature CD11c-negative plasmacytoid dendritic cell",
  "immature CD8_alpha-negative CD11b-positive dendritic cell",
  "CD8_alpha-negative CD11b-negative dendritic cell",
  "CD4-positive CD11b-positive dendritic cell",
  "CD8_alpha-positive CD11b-negative dendritic cell",
  "immature CD8_alpha-negative CD11b-negative dendritic cell",
  "mature CD8_alpha-negative CD11b-negative dendritic cell",
  "mature CD8_alpha-negative CD11b-positive dendritic cell",
  "immature CD8_alpha-positive CD11b-negative dendritic cell",
  "mature CD8_alpha-positive CD11b-negative dendritic cell",
  "dermal dendritic cell",
  "interstitial dendritic cell",
  "Kit and Sca1-positive hematopoietic stem cell",
  "immature dermal dendritic cell",
  "mature dermal dendritic cell",
  "immature interstitial dendritic cell",
  "CD7-negative lymphoid progenitor OR granulocyte monocyte progenitor",
  "mature interstitial dendritic cell",
  "CD1a-positive Langerhans cell",
  "CD8_alpha-low Langerhans cell",
  "immature CD1a-positive Langerhans cell",
  "mature CD1a-positive Langerhans cell",
  "immature CD8_alpha-low Langerhans cell",
  "CD115-positive monocyte OR common dendritic progenitor",
  "mature CD8_alpha-low Langerhans cell",
  "CD34-positive, CD38-positive common lymphoid progenitor",
  "CD115-positive monocyte",
  "Kit-positive, CD34-positive common myeloid progenitor",
  "CD34-positive, CD38-negative hematopoietic stem cell",
  "Kit-positive, Sca1-positive common lymphoid progenitor",
  "CD34-positive, CD38-positive common myeloid progenitor",
  "CD7-negative lymphoid progenitor cell",
  "CD7-positive lymphoid progenitor cell",
  "common dendritic progenitor",
  "CD117-positive common myeloid progenitor OR CD217-positive common lymphoid progenitor",
  "cerebellar granule cell",
  "cortical granule cell",
  "hippocampal granule cell",
  "cell in vitro",
  "bone cell",
  "terminally differentiated osteoblast",
  "non-terminally differentiated osteoblast",
  "CD8-positive, CXCR3-positive, alpha-beta regulatory T cell",
  "T-helper 22 cell",
  "activated CD4-positive, alpha-beta T cell, human",
  "effector CD4-positive, alpha-beta T cell",
  "naive CCR4-positive regulatory T cell",
  "memory CCR4-positive regulatory T cell",
  "CD4-positive, CD25-positive, CCR4-positive, alpha-beta regulatory T cell",
  "activated CD4-positive, CD25-positive, CCR4-positive, alpha-beta regulatory T cell, human",
  "activated CD8-positive, alpha-beta T cell, human",
  "effector CD8-positive, alpha-beta T cell",
  "CD4-positive, CXCR3-negative, CCR6-negative, alpha-beta T cell",
  "CD8-positive, CXCR3-negative, CCR6-negative, alpha-beta T cell",
  "IgD-negative memory B cell",
  "CD14-positive monocyte",
  "CD14-positive, CD16-low monocyte",
  "dendritic cell, human",
  "myeloid dendritic cell, human",
  "plasmacytoid dendritic cell, human",
  "common myeloid progenitor, CD34-positive",
  "hematopoietic oligopotent progenitor cell, lineage-negative",
  "abnormal cell",
  "effector memory CD8-positive, alpha-beta T cell, terminally differentiated",
  "neoplastic cell",
  "malignant cell",
  "innate lymphoid cell",
  "erythroid progenitor cell, mammalian",
  "group 1 innate lymphoid cell",
  "ILC1",
  "group 2 innate lymphoid cell",
  "beige adipocyte",
  "group 3 innate lymphoid cell",
  "visual pigment cell (sensu Nematoda and Protostomia)",
  "Kit-positive erythroid progenitor cell",
  "CD34-positive, CD38-positive granulocyte monocyte progenitor",
  "Kit-positive granulocyte monocyte progenitor",
  "CD34-positive, GlyA-negative erythroid progenitor cell",
  "CD34-negative, GlyA-negative proerythroblast",
  "CD34-positive, CD38-positive megakaryocyte erythroid progenitor cell",
  "Kit-positive, CD34-negative megakaryocyte erythroid progenitor cell",
  "Kit-low, CD34-positive eosinophil progenitor cell",
  "CD34-positive, CD38-positive eosinophil progenitor cell",
  "macrophage dendritic cell progenitor",
  "pre-conventional dendritic cell",
  "Kit-positive macrophage dendritic cell progenitor",
  "Kit-low proerythroblast",
  "GlyA-positive basophillic erythroblast",
  "Kit-negative, Ly-76 high basophilic erythroblast",
  "Kit-negative, Ly-76 high polychromatophilic erythroblast",
  "CD71-low, GlyA-positive polychromatic erythroblast",
  "Kit-negative, Ly-76 high orthochromatophilic erythroblasts",
  "CD71-negative, GlyA-positive orthochromatic erythroblast",
  "Ly-76 high reticulocyte",
  "GlyA-positive reticulocytes",
  "GlyA-positive erythrocyte",
  "Ly-76 high positive erythrocyte",
  "CD34-positive, CD41-positive, CD42-positive megakaryocyte progenitor cell",
  "Kit-positive megakaryocyte progenitor cell",
  "CD34-positive, CD41-positive, CD42-negative megakaryocyte progenitor cell",
  "CD34-negative, CD41-positive, CD42-positive megakaryocyte cell",
  "CD9-positive, CD41-positive megakaryocyte cell",
  "basophil mast progenitor cell",
  "Fc-epsilon RIalpha-low mast cell progenitor",
  "Fc-epsilon RIalpha-high basophil progenitor cell",
  "hematopoietic lineage restricted progenitor cell",
  "hematopoietic oligopotent progenitor cell",
  "short term hematopoietic stem cell",
  "long term hematopoietic stem cell",
  "Slamf1-negative multipotent progenitor cell",
  "Slamf1-positive multipotent progenitor cell",
  "CD2-positive, CD5-positive, CD44-positive alpha-beta intraepithelial T cell",
  "T follicular helper cell",
  "immature NK T cell stage I",
  "immature NK T cell stage II",
  "immature NK T cell stage III",
  "immature NK T cell stage IV",
  "CD34-positive, CD38-negative multipotent progenitor cell",
  "Kit-positive, integrin beta7-high basophil mast progenitor cell",
  "Fraction A pre-pro B cell",
  "early pro-B cell",
  "Fraction B precursor B cell",
  "late pro-B cell",
  "Fraction C precursor B cell",
  "Fraction C' precursor B cell",
  "CD38-high pre-BCR positive cell",
  "Fraction D precursor B cell",
  "CD22-positive, CD38-low small pre-B cell",
  "Fraction E immature B cell",
  "CD38-negative immature B cell",
  "Fraction F mature B cell",
  "CD14-positive, CD16-negative classical monocyte",
  "Gr1-low non-classical monocyte",
  "CD8alpha-positive thymic conventional dendritic cell",
  "melanophage",
  "T-helper 9 cell",
  "type I pneumocyte",
  "type II pneumocyte",
  "pancreatic acinar cell",
  "Feyrter cell",
  "type A enteroendocrine cell",
  "Purkinje myocyte",
  "type II vestibular sensory cell",
  "type I vestibular sensory cell",
  "enterocyte of epithelium of large intestine",
  "nodal myocyte",
  "transitional myocyte",
  "myocardial endocrine cell",
  "brush cell of trachebronchial tree",
  "endo-epithelial cell",
  "ecto-epithelial cell",
  "meso-epithelial cell",
  "pancreatic ductal cell",
  "pancreatic centro-acinar cell",
  "type II cell of carotid body",
  "type II cell of adrenal medulla",
  "type I cell of adrenal medulla",
  "Boettcher cell",
  "tanycyte",
  "specialized cardiac myocyte",
  "nongranular leukocyte",
  "interstitial cell of Cajal",
  "group 2 innate lymphoid cell, mouse",
  "polar body",
  "primary polar body",
  "bone marrow cell",
  "secondary polar body",
  "interstitial cell of ovary",
  "hilus cell of ovary",
  "internodal tract myocyte",
  "cortical cell of adrenal gland",
  "regular cardiac myocyte",
  "type I cell of adrenal cortex",
  "regular interventricular cardiac myocyte",
  "CD38-positive naive B cell",
  "CD38-negative naive B cell",
  "IgG-positive double negative memory B cell",
  "IgG-negative double negative memory B cell",
  "CD38-positive IgG memory B cell",
  "IgD-positive CD38-positive IgG memory B cell",
  "IgD-negative CD38-positive IgG memory B cell",
  "CD38-negative IgG memory B cell",
  "B220-positive CD38-positive naive B cell",
  "B220-low CD38-positive naive B cell",
  "CD38-negative unswitched memory B cell",
  "B220-positive CD38-negative unswitched memory B cell",
  "B220-low CD38-negative unswitched memory B cell",
  "CD38-positive unswitched memory B cell",
  "B220-positive CD38-positive unswitched memory B cell",
  "B220-low CD38-positive unswitched memory B cell",
  "IgG-negative class switched memory B cell",
  "CD38-negative IgG-negative class switched memory B cell",
  "CD38-positive IgG-negative class switched memory B cell",
  "CD24-positive CD38-negative IgG-negative class switched memory B cell",
  "CD24-negative CD38-negative IgG-negative class switched memory B cell",
  "B220-positive CD38-positive IgG-negative class switched memory B cell",
  "B220-low CD38-positive IgG-negative class switched memory B cell",
  "CD27-positive gamma-delta T cell",
  "CD27-negative gamma-delta T cell",
  "CD25-positive, CD27-positive immature gamma-delta T cell",
  "innate effector T cell",
  "Tc17 cell",
  "regular atrial cardiac myocyte",
  "regular interatrial cardiac myocyte",
  "regular ventricular cardiac myocyte",
  "stromal cell of ovary",
  "stromal cell of ovarian cortex",
  "stromal cell of ovarian medulla",
  "nonkeratinized cell of epidermis",
  "type II cell of adrenal cortex",
  "type III cell of adrenal cortex",
  "endothelial cell of lymphatic vessel",
  "endothelial cell of vascular tree",
  "acinar cell of sebaceous gland",
  "active chief cell of parathyroid gland",
  "dark cell of eccrine sweat gland",
  "dark chief cell of parathyroid cell",
  "capillary endothelial cell",
  "ciliated columnar cell of tracheobronchial tree",
  "clear cell of eccrine sweat gland",
  "clear chief cell of parathyroid cell",
  "dental pulp cell",
  "epithelial cell of uterus",
  "epithelioid macrophage",
  "late promyelocyte",
  "columnar cell of endocervix",
  "corneocyte",
  "early promyelocyte",
  "echinocyte",
  "endosteal cell",
  "external epithelial cell of tympanic membrane",
  "general ecto-epithelial cell",
  "basal external epithelial cell of tympanic membrane",
  "superficial external epithelial cell of tympanic membrane",
  "internal epithelial cell of tympanic membrane",
  "internal pillar cell of cochlea",
  "external pillar cell of cochlea",
  "phalangeal cell",
  "epithelial cell of Malassez",
  "olfactory epithelial cell",
  "border cell of cochlea",
  "basal cell of olfactory epithelium",
  "keratinized cell of the oral mucosa",
  "globose cell of olfactory epithelium",
  "interdental cell of cochlea",
  "extraglomerular mesangial cell",
  "follicular cell of ovary",
  "primary follicular cell of ovary",
  "secondary follicular cell of ovary",
  "folliculostellate cell of pars distalis of adenohypophysis",
  "epithelial cell of stomach",
  "foveolar cell of stomach",
  "mucous cell of stomach",
  "mucus neck cell of gastric gland",
  "surface mucosal cell of stomach",
  "stem cell of gastric gland",
  "basal proper cell of olfactory epithelium",
  "basal cell of epidermis",
  "glomerular endothelial cell",
  "granular cell of epidermis",
  "squamous cell of epidermis",
  "granulocytopoietic cell",
  "metamyelocyte",
  "myelocyte",
  "monopoietic cell",
  "hepatic stem cell",
  "hepatic oval stem cell",
  "inactive chief cell of parathyoid gland",
  "oncocyte",
  "oxyphil cell of parathyroid gland",
  "oxyphil cell of thyroid",
  "renal beta-intercalated cell",
  "epithelial cell of tracheobronchial tree",
  "Brush cell of epithelium proper of large intestine",
  "brush cell",
  "brush cell of lobular bronchiole",
  "brush cell of terminal bronchiole",
  "brush cell of trachea",
  "brush cell of bronchus",
  "intermediate epitheliocyte",
  "red muscle cell",
  "type I muscle cell",
  "type II muscle cell",
  "white muscle cell",
  "type IIa muscle cell",
  "type IIb muscle cell",
  "intermediate muscle cell",
  "intermediate trophoblast cell",
  "immature dendritic epithelial T cell precursor",
  "anchoring trophoblast",
  "interstitial cell of pineal gland",
  "keratinized squamous cell of esophagus",
  "vertebrate lens cell",
  "anterior lens cell",
  "lens epithelial cell",
  "secondary lens fiber",
  "non-nucleated secondary lens fiber",
  "nucleated secondary lens fiber",
  "primary lens fiber",
  "light chief cell of parathyroid gland",
  "epithelial cell of prostate",
  "epithelial cell of prostatic duct",
  "epithelial cell of prostatic acinus",
  "basal cell of prostatic acinus",
  "luminal cell of prostatic acinus",
  "basal epithelial cell of prostatic duct",
  "luminal epithelial cell of prostatic duct",
  "male gonocyte",
  "ooblast",
  "marrow fibroblast",
  "pulmonary interstitial fibroblast",
  "nucleate cell",
  "smooth muscle cell of sphincter of pupil",
  "squamous cell of ectocervix",
  "peripheral blood stem cell",
  "pleural macrophage",
  "pluripotent stem cell",
  "primitive cardiac myocyte",
  "intestinal crypt stem cell",
  "epithelial cell of alimentary canal",
  "epithelial cell of esophagus",
  "epithelial cell of large intestine",
  "epithelial cell of small intestine",
  "stromal cell of endometrium",
  "supporting cell of carotid body",
  "epithelial cell of thyroid gland",
  "thyroid follicular cell",
  "neuroepithelial stem cell",
  "epithelial cell of parathyroid gland",
  "endothelial cell of viscerocranial mucosa",
  "endothelial cell of sinusoid",
  "transitional cell of parathyroid gland",
  "type A cell of stomach",
  "type D cell of colon",
  "type D cell of small intestine",
  "type D cell of stomach",
  "P/D1 enteroendocrine cell",
  "vasoactive intestinal peptide secreting cell",
  "type EC2 enteroendocrine cell",
  "type EC1 enteroendocrine cell",
  "motilin secreting cell",
  "type ECL enteroendocrine cell",
  "histamine secreting cell",
  "pancreatic PP cell",
  "type I enteroendocrine cell",
  "GIP cell",
  "type L enteroendocrine cell",
  "type N enteroendocrine cell",
  "type S enteroendocrine cell",
  "type TG enteroendocrine cell",
  "ecto-epithelial cell of viscerocranial mucosa",
  "type X enteroendocrine cell",
  "type III taste bud cell",
  "type II taste cell",
  "type IV taste receptor cell",
  "type V taste receptor cell",
  "type I taste bud cell",
  "Y chromosome-bearing sperm cell",
  "X chromosome-bearing sperm cell",
  "type I cell of carotid body",
  "epithelial cell of thymus",
  "type-1 epithelial cell of thymus",
  "type-6 epithelial cell of thymus",
  "type-4 epithelial cell of thymus",
  "type-3 epithelial cell of thymus",
  "type-5 epithelial cell of thymus",
  "type-2 epithelial cell of thymus",
  "type-7 epithelial cell of thymus",
  "type B synovial cell",
  "type A synovial cell",
  "pigmented ciliary epithelial cell",
  "non-pigmented ciliary epithelial cell",
  "epithelial cell of distal tubule",
  "epithelial cell of proximal tubule",
  "brush border cell of the proximal tubule",
  "epithelial cell of skin gland",
  "corticotroph",
  "mammosomatotroph",
  "mammotroph",
  "somatotroph",
  "endocrine-paracrine cell of prostate gland",
  "external supporting cell of vestibular epithelium",
  "supporting cell of cochlea",
  "supporting cell of vestibular epithelium",
  "external limiting cell of vestibular epithelium",
  "periperhal blood mesothelial cell",
  "neural cell",
  "connective tissue cell",
  "embryonic cell",
  "embryonic stem cell",
  "amniocyte",
  "myoepithelial cell of mammary gland",
  "mammary alveolar cell",
  "luminal epithelial cell of mammary gland",
  "mammary gland epithelial cell",
  "bronchial epithelial cell",
  "basal epithelial cell of tracheobronchial tree",
  "undifferentiated cell of bronchus epithelium",
  "ciliated cell of the bronchus",
  "neural crest derived fat cell",
  "preadipocyte",
  "brown preadipocyte",
  "buccal mucosa cell",
  "keratinocyte stem cell",
  "CD56-positive, CD161-positive immature natural killer cell",
  "prostate stem cell",
  "luminal cell of prostate epithelium",
  "basal cell of prostate epithelium",
  "circulating endothelial cell",
  "decidual natural killer cell",
  "CD56-negative, CD161-positive immature natural killer cell",
  "CD27-low, CD11b-low immature natural killer cell",
  "Dx5-negative, NK1.1-positive immature natural killer cell",
  "CD27-high, CD11b-high natural killer cell",
  "CD27-low, CD11b-high natural killer cell",
  "CD27-high, CD11b-low natural killer cell",
  "endocardial cell",
  "progenitor cell of endocrine pancreas",
  "gestational hematopoietic stem cell",
  "fetal liver hematopoietic progenitor cell",
  "yolk sac hematopoietic stem cell",
  "primitive red blood cell",
  "primitive reticulocyte",
  "fetal derived definitive erythrocyte",
  "pyrenocyte",
  "placental hematopoietic stem cell",
  "AGM hematopoietic stem cell",
  "primitive erythroid progenitor",
  "granule cell precursor",
  "keratocyte",
  "cortical thymic epithelial cell",
  "medullary thymic epithelial cell",
  "myometrial cell",
  "trabecular meshwork cell",
  "respiratory epithelial cell",
  "fungal spore",
  "respiratory goblet cell",
  "somatic cell",
  "myotube",
  "growth hormone releasing hormone secreting cell",
  "ear hair cell",
  "Schwann cell precursor",
  "non-myelinating Schwann cell",
  "immature Schwann cell",
  "immature Vgamma2-positive fetal thymocyte",
  "meningothelial cell",
  "oospore",
  "uninucleate conidium",
  "multinucleate conidium",
  "conidium of conidiophore head",
  "uninucleate macroconidium",
  "blastoconidium",
  "multinucleate macroconidium",
  "arthroconidium",
  "multinucleate arthroconidium",
  "uninucleate arthroconidium",
  "uninucleate blastconidium",
  "multinucleate blastoconidium",
  "intermediate monocyte",
  "CD141-positive myeloid dendritic cell",
  "Gr1-high classical monocyte",
  "CD14-low, CD16-positive monocyte",
  "CD14-positive, CD16-positive monocyte",
  "Gr1-positive, CD43-positive monocyte",
  "CD1c-positive myeloid dendritic cell",
  "Fraction B/C precursor B cell",
  "mature dendritic epithelial T cell precursor",
  "Peyer's patch B cell",
  "mature Vgamma2-positive fetal thymocyte",
  "fetal thymocyte",
  "gamma-delta thymocyte",
  "immature Vgamma2-positive thymocyte",
  "mature Vgamma2-positive thymocyte",
  "immature Vgamma2-negative thymocyte",
  "mature Vgamma2-negative thymocyte",
  "pancreatic stellate cell",
  "Vgamma1.1-positive, Vdelta6.3-negative thymocyte",
  "Vgamma1.1-positive, Vdelta6.3-positive thymocyte",
  "mature Vgamma1.1-positive, Vdelta6.3-negative thymocyte",
  "immature Vgamma1.1-positive, Vdelta6.3-negative thymocyte",
  "immature Vgamma1.1-positive, Vdelta6.3-positive thymocyte",
  "mature Vgamma1.1-positive, Vdelta6.3-positive thymocyte",
  "primitive erythroid lineage cell",
  "hemangioblast",
  "mature T cell",
  "immature T cell",
  "nucleated reticulocyte",
  "enucleated reticulocyte",
  "DN2a thymocyte",
  "DN2b thymocyte",
  "early T lineage precursor",
  "CD11b-positive, CD27-positive natural killer cell",
  "resting double-positive thymocyte",
  "double-positive blast",
  "CD69-positive double-positive thymocyte",
  "CD4-intermediate, CD8-positive double-positive thymocyte",
  "CD4-positive, CD8-intermediate double-positive thymocyte",
  "CD24-positive, CD4 single-positive thymocyte",
  "CD69-positive, CD4-positive single-positive thymocyte",
  "CD24-positive, CD8 single-positive thymocyte",
  "CD69-positive, CD8-positive single-positive thymocyte",
  "mature CD4 single-positive thymocyte",
  "mature CD8 single-positive thymocyte",
  "NK1.1-positive natural killer cell",
  "NKGA2-positive natural killer cell",
  "Ly49D-positive natural killer cell",
  "CD94-positive natural killer cell",
  "CD94-negative, Ly49CI-negative natural killer cell",
  "Ly49CI-positive natural killer cell",
  "Ly49H-positive natural killer cell",
  "Ly49D-negative natural killer cell",
  "Ly49CI-negative natural killer cell",
  "CD94-negative natural killer cell",
  "Ly49H-negative natural killer cell",
  "CD94-positive Ly49CI-positive natural killer cell",
  "tether cell",
  "mammary stem cell",
  "oligodendrocyte precursor cell",
  "Cd4-negative, CD8_alpha-negative, CD11b-positive dendritic cell",
  "CD8_alpha-negative plasmactyoid dendritic cell",
  "CD8_alpha-positive plasmactyoid dendritic cell",
  "epidermal Langerhans cell",
  "langerin-positive dermal dendritic cell",
  "langerin-negative dermal dendritic cell",
  "CD8alpha-negative thymic conventional dendritic cell",
  "CD103-positive dendritic cell",
  "adipose dendritic cell",
  "SIRPa-positive adipose dendritic cell",
  "SIRPa-negative adipose dendritic cell",
  "CD11b-positive dendritic cell",
  "small intestine serosal dendritic cell",
  "Gr1-high myeloid suppressor cell",
  "Gr1-low myeloid suppressor cell",
  "MHC-II-negative classical monocyte",
  "MHC-II-positive classical monocyte",
  "MHC-II-negative non-classical monocyte",
  "MHC-II-low non-classical monocyte",
  "MHC-II-high non-classical monocyte",
  "lymphoid MHC-II-negative classical monocyte",
  "lymphoid MHC-II-negative non-classical monocyte",
  "bone marrow macrophage",
  "adipose macrophage",
  "F4/80-negative adipose macrophage",
  "F4/80-positive adipose macrophage",
  "nasal mucosa goblet cell",
  "peritubular myoid cell",
  "dermal melanocyte",
  "hair follicle melanocyte",
  "epithelial melanocyte",
  "retinal melanocyte",
  "strial intermediate cell",
  "cutaneous/subcutaneous mechanoreceptor cell",
  "trophoblast giant cell",
  "double negative thymocyte",
  "organ of Corti supporting cell",
  "auditory epithelial cell",
  "strial marginal cell",
  "strial basal cell",
  "cardiocyte",
  "fetal cardiomyocyte",
  "intraepithelial lymphocyte",
  "primary trophoblast giant cell",
  "secondary trophoblast giant cell",
  "spongiotrophoblast cell",
  "P enteroendocrine cell",
  "type D1 enteroendocrine cell",
  "type M enteroendocrine cell",
  "adventitial cell",
  "enteric smooth muscle cell",
  "liver CD103-negative dendritic cell",
  "liver CD103-positive dendritic cell",
  "langerin-positive lymph node dendritic cell",
  "langerin-negative, CD103-negative lymph node dendritic cell",
  "CD103-positive, langerin-positive lymph node dendritic cell",
  "CD103-negative, langerin-positive lymph node dendritic cell",
  "CD11b-low, CD103-negative, langerin-negative lymph node dendritic cell",
  "CD11b-high, CD103-negative, langerin-negative lymph node dendritic cell",
  "Vgamma5-positive CD8alpha alpha positive gamma-delta intraepithelial T cell",
  "Vgamma5-negative CD8alpha alpha positive gamma-delta intraepithelial T cell",
  "interrenal norepinephrine type cell",
  "interrenal chromaffin cell",
  "interrenal epinephrin secreting cell",
  "kidney epithelial cell",
  "interrenal epithelial cell",
  "nephrocyte",
  "subcutaneous fat cell",
  "renal filtration cell",
  "mesonephric glomerular visceral epithelial cell",
  "disseminated nephrocyte",
  "metanephric glomerular visceral epithelial cell",
  "CD14-positive dermal dendritic cell",
  "immature CD14-positive dermal dendritic cell",
  "mature CD14-positive dermal dendritic cell",
  "CD1a-positive dermal dendritic cell",
  "immature CD1a-positive dermal dendritic cell",
  "mature CD1a-positive dermal dendritic cell",
  "CD16-positive myeloid dendritic cell",
  "immature CD16-positive myeloid dendritic cell",
  "mature CD16-positive myeloid dendritic cell",
  "epithelial cell of cervix",
  "epithelial cell of amnion",
  "amnion mesenchymal stem cell",
  "intrahepatic bile duct epithelial cell",
  "aortic smooth muscle cell",
  "mesenchymal stem cell of the bone marrow",
  "chorionic membrane mesenchymal stem cell",
  "vein endothelial cell",
  "aortic endothelial cell",
  "thoracic aorta endothelial cell",
  "embryonic blood vessel endothelial progenitor cell",
  "fibroblast of the aortic adventitia",
  "fibroblast of cardiac tissue",
  "fibroblast of choroid plexus",
  "fibroblast of the conjunctiva",
  "fibroblast of dermis",
  "fibroblast of gingiva",
  "fibroblast of lung",
  "fibroblast of lymphatic vessel",
  "fibroblast of mammary gland",
  "fibroblast of periodontium",
  "fibroblast of pulmonary artery",
  "fibroblast of villous mesenchyme",
  "hair follicle cell",
  "inner root sheath cell",
  "outer root sheath cell",
  "hair germinal matrix cell",
  "intestinal epithelial cell",
  "nucleus pulposus cell of intervertebral disc",
  "iris pigment epithelial cell",
  "dark melanocyte",
  "light melanocyte",
  "mesenchymal stem cell of Wharton's jelly",
  "mesenchymal stem cell of umbilical cord",
  "mesenchymal stem cell of adipose",
  "hepatic mesenchymal stem cell",
  "vertebral mesenchymal stem cell",
  "Schwann cell",
  "stromal cell of pancreas",
  "central nervous system pericyte",
  "perineural cell",
  "placental epithelial cell",
  "mesenteric preadipocyte",
  "omentum preadipocyte",
  "preadipocyte of the breast",
  "perirenal preadipocyte",
  "visceral preadipocyte",
  "subcutaneous preadipocyte",
  "renal cortical epithelial cell",
  "retinal blood vessel endothelial cell",
  "retinal pigment epithelial cell",
  "smooth muscle cell of the umbilical vein",
  "smooth muscle cell of the brachiocephalic vasculature",
  "smooth muscle cell of the brain vasculature",
  "smooth muscle cell of the pulmonary artery",
  "smooth muscle cell of the coronary artery",
  "smooth muscle cell of the internal thoracic artery",
  "smooth muscle cell of the umbilical artery",
  "smooth muscle cell of the subclavian artery",
  "smooth muscle cell of the carotid artery",
  "smooth muscle cell of bladder",
  "bronchial smooth muscle cell",
  "smooth muscle cell of the esophagus",
  "smooth muscle cell of trachea",
  "uterine smooth muscle cell",
  "annulus pulposus cell",
  "astrocyte of the cerebellum",
  "astrocyte of the hippocampus",
  "astrocyte of the cerebral cortex",
  "astrocyte of the spinal cord",
  "migratory enteric neural crest cell",
  "hippocampal neuron",
  "neuron of cerebral cortex",
  "raphe nuclei neuron",
  "neuron of the dorsal spinal cord",
  "neuron of the ventral spinal cord",
  "striatum neuron",
  "neuron of the substantia nigra",
  "adipocyte of omentum tissue",
  "perirenal adipocyte cell",
  "adipocyte of breast",
  "endothelial cell of umbilical vein",
  "adult endothelial progenitor cell",
  "skin fibroblast",
  "gingival epithelial cell",
  "prostate stromal cell",
  "acinar cell of salivary gland",
  "paneth cell of the appendix",
  "seminiferous tubule epithelial cell",
  "immature astrocyte",
  "mature astrocyte",
  "immature microglial cell",
  "mature microglial cell",
  "actinomycete-type spore",
  "epithelial cell of upper respiratory tract",
  "epithelial cell of lower respiratory tract",
  "respiratory basal cell",
  "epithelial cell of anal column",
  "nonkeratinized epithelial cell of anal column",
  "nonkeratinized epithelial cell of inferior part of anal canal",
  "keratinized epithelial cell of the anal canal",
  "bronchioalveolar stem cell",
  "amniotic stem cell",
  "amniotic epithelial stem cell",
  "epithelial cell of esophageal gland proper",
  "epithelial cell of esophageal cardiac gland",
  "nonkeratinized cell of stratum corneum of esophageal epithelium",
  "endo-epithelial cell of tympanic part of viscerocranial mucosa",
  "endo-epithelial cell of pharyngotympanic part of viscerocranial mucosa",
  "endothelial cell of venous sinus of spleen",
  "endothelial cell of high endothelial venule",
  "squamous endothelial cell",
  "epithelial cell of stratum corneum of esophageal epithelium",
  "epithelial cell of stratum spinosum of esophageal epithelium",
  "glandular cell of endometrium",
  "glandular cell of esophagus",
  "glandular cell of the large intestine",
  "glandular cell of stomach",
  "luminal cell of acinus of lactiferous gland",
  "luminal cell of lactiferous terminal ductal lobular unit",
  "luminal cell of lactiferous duct",
  "myocardial endocrine cell of atrium",
  "cardioblast",
  "otic fibrocyte",
  "type 2 otic fibrocyte",
  "type 5 otic fibrocyte",
  "type 4 otic fibrocyte",
  "type 3 otic fibrocyte",
  "type 1 otic fibrocyte",
  "endothelial stalk cell",
  "retinal progenitor cell",
  "tongue muscle cell",
  "H minus",
  "H plus",
  "neural crest derived neuroblast",
  "naive regulatory T cell",
  "memory regulatory T cell",
  "natural helper lymphocyte",
  "PP cell of intestine",
  "kidney cortical cell",
  "spinal cord interneuron",
  "iridoblast",
  "xanthoblast",
  "leucoblast",
  "pigment erythroblast",
  "cyanoblast",
  "ionocyte",
  "Kolmer-Agduhr neuron",
  "macular hair cell",
  "renal principal cell",
  "renal intercalated cell",
  "renal alpha-intercalated cell",
  "multi-ciliated epithelial cell",
  "single ciliated epithelial cell",
  "auditory epithelial support cell",
  "inner phalangeal cell",
  "ghrelin secreting cell",
  "pancreatic epsilon cell",
  "lymphangioblast",
  "mesenchymal lymphangioblast",
  "vascular lymphangioblast",
  "branchiomotor neuron",
  "somatomotor neuron",
  "visceromotor neuron",
  "hepatoblast",
  "preameloblast",
  "skeletogenic cell",
  "precementoblast",
  "preodontoblast",
  "premigratory neural crest cell",
  "notochordal cell",
  "chordamesodermal cell",
  "notochordal sheath cell",
  "notochordal vacuole cell",
  "prechondroblast",
  "preosteoblast",
  "enteric neuron",
  "non-terminally differentiated odontoblast",
  "terminally differentiated odontoblast",
  "adaxial cell",
  "Stiftchenzellen",
  "epidermal ciliary cell",
  "epidermal mucus secreting cell",
  "bottle cell",
  "alarm substance cell",
  "micropylar cell",
  "flask cell",
  "non-striated muscle cell",
  "hematopoietic precursor cell",
  "skeletal muscle fiber",
  "somatic muscle myotube",
  "somatic muscle cell",
  "obliquely striated somatic muscle cell",
  "muscle founder cell",
  "visceral muscle cell",
  "striated visceral muscle cell",
  "transversely striated visceral muscle cell",
  "cranial somatomotor neuron",
  "skeletal muscle satellite stem cell",
  "quiescent skeletal muscle satellite cell",
  "cranial visceromotor neuron",
  "excitatory motor neuron",
  "inhibitory motor neuron",
  "activated skeletal muscle satellite cell",
  "adult skeletal muscle myoblast",
  "somatic muscle myoblast",
  "mesenchymal cell",
  "skeletal muscle satellite myogenic cell",
  "anterior lateral line ganglion neuron",
  "endocardial cushion cell",
  "pancreatic endocrine cell",
  "noradrenergic neuron",
  "open tracheal system tracheocyte",
  "rod bipolar cell (sensu Mus)",
  "visual system neuron",
  "inhibitory neuron",
  "excitatory neuron",
  "cortical interneuron",
  "rosehip neuron",
  "sensory neuron of spinal nerve",
  "compound eye retinal cell",
  "inflammatory cell",
  "larval midgut cell",
  "retinal cell",
  "salivary gland cell",
  "keratinized cell of hair follicle",
  "stromal cell of bone marrow",
  "epithelial cell of umbilical artery",
  "epithelial cell of alveolus of lung",
  "mononuclear cell of bone marrow",
  "atrioventricular bundle cell",
  "cardiac blood vessel endothelial cell",
  "His-Purkinje system cell",
  "cardiac endothelial cell",
  "camera-type eye photoreceptor cell",
  "cerebellar stellate cell",
  "cerebral cortex GABAergic interneuron",
  "cerebral cortex neuron",
  "type I pinealocyte",
  "type II pinealocyte",
  "coronet cell",
  "collar cell",
  "cardiac glial cell",
  "cardiac myoblast",
  "cardiac neuron",
  "dorsal horn interneuron",
  "spinal cord motor neuron",
  "lateral motor column neuron",
  "magnocellular neurosecretory cell (duplicate class)",
  "lens fiber cell",
  "GABAergic interneuron",
  "Lugaro cell",
  "paraxial cell",
  "embryonic hemocyte",
  "embryonic plasmatocyte",
  "lateral mesodermal cell",
  "intermediate mesodermal cell",
  "neural crest cell",
  "galanergic neuron",
  "chorionic trophoblast cell",
  "parasympathetic neuron",
  "sympathetic neuron",
  "interplexiform cell",
  "dopamanergic interplexiform cell",
  "GABAnergic interplexiform cell",
  "Muller cell",
  "colon epithelial cell",
  "hypocretin-secreting neuron",
  "histaminergic neuron",
  "gonadotropin releasing neuron",
  "magnocellular neurosecretory cell",
  "spiral ganglion neuron",
  "segmented neutrophil of bone marrow",
  "precursor cell",
  "astrocyte of the forebrain",
  "neuron of the forebrain",
  "forebrain radial glial cell",
  "cranial motor neuron",
  "retrotrapezoid nucleus neuron",
  "mesonephric nephron tubule epithelial cell",
  "forebrain neuroblast",
  "lateral line nerve glial cell",
  "spinal cord radial glial cell",
  "stretch receptor cell",
  "stratified keratinized epithelial stem cell",
  "stratified non keratinized epithelial stem cell",
  "pronephric nephron tubule epithelial cell",
  "metanephric nephron tubule epithelial cell",
  "lung goblet cell",
  "heart valve cell",
  "Malpighian tubule stellate cell",
  "malpighian tubule tip cell",
  "pillar cell",
  "growth plate cartilage chondrocyte",
  "stomach neuroendocrine cell",
  "lung neuroendocrine cell",
  "posterior lateral line nerve glial cell",
  "anterior lateral line nerve glial cell",
  "posterior lateral line ganglion neuron",
  "lung ciliated cell",
  "lung secretory cell",
  "trophectodermal cell",
  "smooth muscle cell of small intestine",
  "smooth muscle fiber of duodenum",
  "smooth muscle fiber of jejunum",
  "smooth muscle fiber of ileum",
  "smooth muscle cell of large intestine",
  "smooth muscle cell of colon",
  "smooth muscle cell of cecum",
  "smooth muscle fiber of ascending colon",
  "smooth muscle fiber of transverse colon",
  "smooth muscle fiber of descending colon",
  "smooth muscle cell of sigmoid colon",
  "smooth muscle cell of rectum",
  "myocyte of anterior internodal tract",
  "myocyte of atrial branch of anterior internodal tract",
  "myocyte of atrial septal branch of anterior internodal tract",
  "myocyte of middle internodal tract",
  "myocyte of posterior internodal tract",
  "epithelial cell of urethra",
  "mesothelial cell of dura mater",
  "fibroblast of connective tissue of prostate",
  "fibroblast of outer membrane of prostatic capsule",
  "fibroblast of subepithelial connective tissue of prostatic gland",
  "fibroblast of papillary layer of dermis",
  "fibroblast of areolar connective tissue",
  "fibroblast of connective tissue of nonglandular part of prostate",
  "fibroblast of connective tissue of glandular part of prostate",
  "fibroblast of tunica adventitia of artery",
  "fibroblast of dense regular elastic tissue",
  "fibrocyte of adventitia of ureter",
  "epicardial adipocyte",
  "adipocyte of epicardial fat of right ventricle",
  "adipocyte of epicardial fat of left ventricle",
  "bronchial goblet cell",
  "gastric goblet cell",
  "gastric cardiac gland goblet cell",
  "principal gastric gland goblet cell",
  "intestinal villus goblet cell",
  "large intestine goblet cell",
  "large intestine crypt goblet cell",
  "pancreatic goblet cell",
  "pylroric gastric gland goblet cell",
  "duodenal goblet cell",
  "jejunal goblet cell",
  "ileal goblet cell",
  "appendix goblet cell",
  "tracheal goblet cell",
  "serous cell of epithelium of trachea",
  "serous cell of epithelium of bronchus",
  "serous cell of epithelium of terminal bronchiole",
  "serous cell of epithelium of lobular bronchiole",
  "enterocyte of epithelium of small intestine",
  "enterocyte of epithelium of intestinal villus",
  "enterocyte of epithelium of duodenal gland",
  "enterocyte of epithelium of crypt of Lieberkuhn of small intestine",
  "enterocyte of epithelium proper of small intestine",
  "enterocyte of epithelium proper of duodenum",
  "enterocyte of epithelium proper of jejunum",
  "enterocyte of epithelium proper of ileum",
  "paneth cell of epithelium of small intestine",
  "paneth cell of epithelium proper of small intestine",
  "paneth cell of epithelium of crypt of Lieberkuhn of small intestine",
  "vacuolar absorptive cell of epithelium proper of large intestine",
  "vacuolar absorptive cell of epithelium of colon",
  "basal cell of epithelium of trachea",
  "basal cell of epithelium of bronchus",
  "basal cell of epithelium of terminal bronchiole",
  "basal cell of epithelium of respiratory bronchiole",
  "basal cell of epithelium of lobular bronchiole",
  "microfold cell of epithelium of small intestine",
  "microfold cell of epithelium of intestinal villus",
  "microfold cell of epithelium proper of small intestine",
  "microfold cell of epithelium proper of duodenum",
  "microfold cell of epithelium proper of jejunum",
  "microfold cell of epithelium proper of ileum",
  "microfold cell of epithelium proper of appendix",
  "microfold cell of epithelium proper of large intestine",
  "transitional myocyte of interatrial septum",
  "transitional myocyte of interventricular septum",
  "transitional myocyte of atrial branch of anterior internodal tract",
  "transitional myocyte of anterior internodal tract",
  "transitional myocyte of atrial septal branch of anterior internodal tract",
  "transitional myocyte of middle internodal tract",
  "transitional myocyte of posterior internodal tract",
  "transitional myocyte of anterior division of left branch of atrioventricular bundle",
  "transitional myocyte of septal division of left branch of atrioventricular bundle",
  "transitional myocyte of left branch of atrioventricular bundle",
  "transitional myocyte of right branch of atrioventricular bundle",
  "transitional myocyte of atrial part of atrioventricular bundle",
  "transitional myocyte of ventricular part of atrioventricular bundle",
  "transitional myocyte of posterior division of left branch of atrioventricular bundle",
  "myocardial endocrine cell of septal division of left branch of atrioventricular bundle",
  "Purkinje myocyte of interventricular septum",
  "dense-core granulated cell of epithelium of trachea",
  "type 1 vestibular sensory cell of stato-acoustic epithelium",
  "type 1 vestibular sensory cell of epithelium of macula of utricle of membranous labyrinth",
  "type 1 vestibular sensory cell of epithelium of macula of saccule of membranous labyrinth",
  "type 1 vestibular sensory cell of epithelium of crista of ampulla of semicircular duct of membranous labyrinth",
  "type 2 vestibular sensory cell of stato-acoustic epithelium",
  "type 2 vestibular sensory cell of epithelium of macula of utricle of membranous labyrinth",
  "type 2 vestibular sensory cell of epithelium of macula of saccule of membranous labyrinth",
  "type 2 vestibular sensory cell of epithelium of crista of ampulla of semicircular duct of membranous labyrinth",
  "melanocyte of eyelid",
  "myoepithelial cell of intralobular lactiferous duct",
  "endothelial cell of venous sinus of red pulp of spleen",
  "endothelial cell of hepatic sinusoid",
  "epithelial cell of appendix",
  "myocyte of sinoatrial node",
  "myocyte of atrioventricular node",
  "endothelial cell of Peyer's patch",
  "endothelial cell of arteriole",
  "endothelial cell of artery",
  "endothelial cell of venule",
  "epithelial cell of gall bladder",
  "myoepithelial cell of lactiferous gland",
  "myoepithelial cell of sweat gland",
  "myoepithelial cell of lactiferous alveolus",
  "myoepithelial cell of lactiferous duct",
  "myoepithelial cell of terminal lactiferous duct",
  "chromaffin cell of paraaortic body",
  "chromaffin cell of paraganglion",
  "chromaffin cell of adrenal gland",
  "adrenal cortex chromaffin cell",
  "stem cell of epidermis",
  "conjunctival epithelial cell",
  "epithelial cell of lacrimal canaliculus",
  "epithelial cell of external acoustic meatus",
  "epithelial cell of lacrimal duct",
  "epithelial cell of lacrimal sac",
  "epithelial cell of nasolacrimal duct",
  "epithelial cell of wall of inferior part of anal canal",
  "epithelial cell of viscerocranial mucosa",
  "urothelial cell of trigone of urinary bladder",
  "ciliary muscle cell",
  "mesothelial cell of anterior chamber of eye",
  "myoepithelial cell of dilator pupillae",
  "epithelial cell of stratum germinativum of esophagus",
  "epithelial cell of sweat gland",
  "epithelial cell of nephron",
  "epithelial cell of glomerular capsule",
  "epithelial cell of visceral layer of glomerular capsule",
  "parietal epithelial cell",
  "epithelial cell of intermediate tubule",
  "kidney collecting duct epithelial cell",
  "mesothelial cell of parietal peritoneum",
  "mesothelial cell of visceral peritoneum",
  "melanocyte of skin",
  "chromaffin cell of ovary",
  "chromaffin cell of right ovary",
  "chromaffin cell of left ovary",
  "myoepithelial cell of acinus of lactiferous gland",
  "myoepithelial cell of main lactiferous duct",
  "myoepithelial cell of primary lactiferous duct",
  "myoepithelial cell of secondary lactiferous duct",
  "myoepithelial cell of tertiary lactiferous duct",
  "myoepithelial cell of quarternary lactiferous duct",
  "cardiac pacemaker cell of sinoatrial node",
  "transitional myocyte of sinoatrial node",
  "Purkinje myocyte of atrioventricular node",
  "transitional myocyte of internodal tract",
  "transitional myocyte of atrioventricular bundle",
  "myocardial endocrine cell of interventricular septum",
  "Purkinje myocyte of internodal tract",
  "Purkinje myocyte of atrioventricular bundle",
  "basal cell of urothelium",
  "smooth muscle cell of prostate",
  "cholangiocyte",
  "reticular cell of splenic cord",
  "mesothelial cell of peritoneum",
  "mesothelial cell of pleura",
  "mesothelial cell of parietal pleura",
  "mesothelial cell of visceral pleura",
  "nephron tubule epithelial cell",
  "small intestine goblet cell",
  "kidney cell",
  "kidney interstitial cell",
  "kidney medulla cell",
  "kidney pelvis cell",
  "kidney tubule cell",
  "kidney glomerular epithelial cell",
  "kidney medulla collecting duct epithelial cell",
  "kidney inner medulla collecting duct epithelial cell",
  "kidney outer medulla collecting duct epithelial cell",
  "kidney cortex collecting duct epithelial cell",
  "kidney papillary duct principal epithelial cell",
  "inner renal cortex cell",
  "papillary tips cell",
  "lower urinary tract cell",
  "ureteral cell",
  "kidney nerve cell",
  "kidney corpuscule cell",
  "kidney cortex tubule cell",
  "kidney outer medulla cell",
  "kidney inner medulla cell",
  "juxtaglomerular complex cell",
  "kidney cortex interstitial cell",
  "kidney medulla interstitial cell",
  "kidney interstitial myofibroblast",
  "kidney interstitial fibroblast",
  "kidney interstitial fibrocyte",
  "kidney interstitial alternatively activated macrophage",
  "kidney interstitial inflammatory macrophage",
  "kidney interstitial suppressor macrophage",
  "kidney resident macrophage",
  "kidney resident dendritic cell",
  "kidney pelvis smooth muscle cell",
  "kidney pelvis urothelial cell",
  "ureter urothelial cell",
  "ureter adventitial cell",
  "kidney cortex collecting duct principal cell",
  "kidney cortex collecting duct intercalated cell",
  "kidney outer medulla collecting duct principal cell",
  "kidney outer medulla collecting duct intercalated cell",
  "kidney inner medulla collecting duct principal cell",
  "kidney inner medulla collecting duct intercalated cell",
  "kidney papillary duct intercalated cell",
  "kidney papillary duct principal cell",
  "glomerular mesangial cell",
  "glomerular cell",
  "kidney connecting tubule epithelial cell",
  "kidney inner medulla interstitial cell",
  "kidney outer medulla interstitial cell",
  "kidney proximal convoluted tubule epithelial cell",
  "kidney proximal straight tubule epithelial cell",
  "kidney distal convoluted tubule epithelial cell",
  "macula densa epithelial cell",
  "kidney blood vessel cell",
  "kidney arterial blood vessel cell",
  "kidney capillary endothelial cell",
  "kidney venous blood vessel cell",
  "kidney loop of Henle epithelial cell",
  "ureter smooth muscle cell",
  "glomerular capillary endothelial cell",
  "kidney afferent arteriole cell",
  "kidney efferent arteriole cell",
  "kidney loop of Henle ascending limb epithelial cell",
  "kidney loop of Henle descending limb epithelial cell",
  "peritubular capillary endothelial cell",
  "vasa recta cell",
  "kidney cortex artery cell",
  "kidney cortex vein cell",
  "kidney artery smooth muscle cell",
  "kidney arteriole smooth muscle cell",
  "kidney venous system smooth muscle cell",
  "kidney afferent arteriole endothelial cell",
  "kidney afferent arteriole smooth muscle cell",
  "kidney efferent arteriole endothelial cell",
  "kidney efferent arteriole smooth muscle cell",
  "kidney loop of Henle thick ascending limb epithelial cell",
  "kidney loop of Henle thin ascending limb epithelial cell",
  "kidney loop of Henle medullary thick ascending limb epithelial cell",
  "kidney loop of Henle cortical thick ascending limb epithelial cell",
  "kidney loop of Henle thin descending limb epithelial cell",
  "kidney outer medulla peritubular capillary cell",
  "kidney cortex peritubular capillary cell",
  "inner renal medulla vasa recta cell",
  "outer renal medulla vasa recta cell",
  "vasa recta ascending limb cell",
  "arcuate artery cell",
  "interlobular artery cell",
  "arcuate vein cell",
  "interlobular vein cell",
  "inner medulla vasa recta ascending limb cell",
  "outer medulla vasa recta ascending limb cell",
  "arcuate artery endothelial cell",
  "arcuate artery smooth muscle cell",
  "interlobulary artery endothelial cell",
  "interlobulary artery smooth muscle cell",
  "arcuate vein endothelial cell",
  "arcuate vein smooth muscle cell",
  "interlobulary vein endothelial cell",
  "interlobulary vein smooth muscle cell",
  "kidney collecting duct cell",
  "vasa recta descending limb cell",
  "inner medulla vasa recta descending limb cell",
  "outer medulla vasa recta descending limb cell",
  "renal interstitial pericyte",
  "bladder cell",
  "urethra cell",
  "bladder urothelial cell",
  "urethra urothelial cell",
  "kidney collecting duct principal cell",
  "kidney collecting duct intercalated cell",
  "epithelial cell of exocrine pancreas",
  "olfactory bulb interneuron",
  "periglomerular cell",
  "hair-tylotrich neuron",
  "hair-down neuron",
  "sensory neuron of dorsal root ganglion",
  "medium spiny neuron",
  "mitral cell",
  "olfactory bulb tufted cell",
  "parvocellular neurosecretory cell",
  "glycinergic neuron",
  "intestinal enteroendocrine cell",
  "stomach enteroendocrine cell",
  "vomeronasal sensory neuron",
  "bronchioalveolar stem cells",
  "lung endothelial cell",
  "pulmonary artery endothelial cell",
  "hippocampal interneuron",
  "hippocampal pyramidal neuron",
  "colon endothelial cell",
  "nasopharyngeal epithelial cell",
  "uterine cervix squamous cell",
  "oral mucosa squamous cell",
  "tonsil squamous cell",
  "vagina squamous cell",
  "cerebral cortex glial cell",
  "hippocampus glial cell",
  "lateral ventricle glial cell",
  "lateral ventricle neuron",
  "appendix glandular cell",
  "mammary gland glandular cell",
  "uterine cervix glandular cell",
  "colon glandular cell",
  "duodenum glandular cell",
  "epididymis glandular cell",
  "oviduct glandular cell",
  "gall bladder glandular cell",
  "parathyroid glandular cell",
  "rectum glandular cell",
  "salivary gland glandular cell",
  "seminal vesicle glandular cell",
  "small intestine glandular cell",
  "pancreas exocrine glandular cell",
  "adrenal gland glandular cell",
  "cerebral cortex endothelial cell",
  "lung macrophage",
  "foreskin keratinocyte",
  "articular chondrocyte",
  "foreskin fibroblast",
  "muscle fibroblast",
  "bone marrow hematopoietic cell",
  "cerebellar neuron",
  "epidermal melanocyte",
  "peripheral blood mononuclear cell",
  "decidua cell",
  "pituitary gland cell",
  "brain macroglial cell",
  "tonsil germinal center B cell",
  "articular chondrocyte of knee joint",
  "microvascular endothelial cell",
  "dermis blood vessel endothelial cell",
  "dermis lymphatic vessel endothelial cell",
  "fibroblast of pedal digit skin",
  "fibroblast of skin of abdomen",
  "fibroblast of upper leg skin",
  "fibroblast of arm",
  "lung microvascular endothelial cell",
  "fibroblast of peridontal ligament",
  "endothelial cell of coronary artery",
  "compound eye photoreceptor cell",
  "inner cell mass native cell",
  "sebaceous gland native cell",
  "cardiac septum native cell",
  "spinal cord ventral column interneuron",
  "spinal cord medial motor column neuron",
  "spinal cord oligodendrocyte",
  "cerebellum basket cell",
  "cerebellum glutamatergic neuron",
  "central nervous system neuron",
  "hypothalamus native cell",
  "lateral line ganglion neuron",
  "peripheral nervous system neuron",
  "limb basal cell of epidermis",
  "anterior lateral line neuromast hair cell",
  "anterior lateral line neuromast mantle cell",
  "anterior lateral line neuromast support cell",
  "posterior lateral line neuromast hair cell",
  "posterior lateral line neuromast mantle cell",
  "posterior lateral line neuromast support cell",
  "bladder microvascular endothelial cell",
  "dermis microvascular lymphatic vessel endothelial cell",
  "embryonic fibroblast",
  "brain pericyte",
  "brain microvascular endothelial cell",
  "foreskin melanocyte",
  "ventricular cardiac muscle cell",
  "brainstem motor neuron",
  "ventral horn of spinal cord spinal cord motor neuron",
  "primary motor cortex pyramidal cell",
  "splenic fibroblast",
  "umbilical artery endothelial cell",
  "splenic endothelial cell",
  "hepatic pit cell",
  "liver dendritic cell",
  "Meynert cell",
  "femural osteoblast",
  "calvarial osteoblast",
  "prostate gland microvascular endothelial cell",
  "placental villous trophoblast",
  "placental amniotic mesenchymal stromal cell",
  "placental villus capillary endothelial cell",
  "ovarian fibroblast",
  "ovarian surface epithelial cell",
  "ovarian microvascular endothelial cell",
  "cardiac ventricle fibroblast",
  "cardiac atrium fibroblast",
  "pericardium fibroblast",
  "gallbladder fibroblast",
  "optic choroid fibroblast",
  "mammary microvascular endothelial cell",
  "adipose microvascular endothelial cell",
  "migratory cardiac neural crest cell",
  "splenocyte",
  "anterior visceral endoderm cell",
  "hindlimb stylopod vein endothelial cell",
  "skeletal muscle tissue of pectoralis major striated muscle cell",
  "placental pericyte",
  "mesenchymal stem cell of femoral bone marrow",
  "mesenchymal stem cell of abdominal adipose",
  "melanocyte of skin of face",
  "melanocyte of foreskin",
  "hair follicle dermal papilla cell of scalp",
  "conjunctiva goblet cell",
  "mononuclear cell of umbilical cord",
  "neocortex basket cell",
  "dentate gyrus of hippocampal formation basket cell",
  "Ammon's horn basket cell",
  "dentate gyrus of hippocampal formation granule cell",
  "dentate gyrus of hippocampal formation stellate cell",
  "endometrial microvascular endothelial cells",
  "hair follicular keratinocyte",
  "bronchus fibroblast of lung",
  "nasal cavity respiratory epithelium epithelial cell of viscerocranial mucosa",
  "cord blood hematopoietic stem cell",
  "reticular layer of dermis fibroblast",
  "midbrain dopaminergic neuron",
  "ciliated epithelial cell of esophagus",
  "Hofbauer cell",
  "sympathetic noradrenergic neuron",
  "sympathetic cholinergic neuron",
  "peripheral sensory neuron"
];
